name: Run Gateway tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  gateway-tests:
    # disable for now
    if: false
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout head
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Start gateway and run tests
        run: |
          npm run build/start-server.js &
          echo "Waiting for gateway to start..."
          while ! curl -s http://localhost:8787 > /dev/null; do
            sleep 1
          done
          echo "Gateway is ready. Running tests..."
          npm run test:gateway

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
